name: Checking

on: push

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run Check
        run: deno check ./src/**/*.ts

      - name: Run publish --dry-run
        run: deno publish --dry-run

      - name: Run tests
        run: deno test --quiet --coverage --parallel ./tests

      - name: Run coverage
        run: |-
          deno coverage --include=./src --lcov --output=cov.lcov
          deno coverage --include=./src

      - name: Run Codecov
        uses: codecov/codecov-action@v4
        with:
          files: cov.lcov
          use_oidc: true

