name: Publish NPM

on:
  push:
    tags:
      - v/*

jobs:

  publish:

    runs-on: ubuntu-latest
    timeout-minutes: 3

    permissions:
      contents: read
      id-token: write

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: v20
          registry-url: https://registry.npmjs.org/

      - name: Prebuild
        run: |-

          VER=$(jq -r '.version' deno.json)

          cat tmp-package.json | sed "s/0.0.0-VERSION/$VER/" > package.json

          npm install --no-{fund,save,lock} typescript@5.7.0-beta @types/node@18

      - name: Build by tsc
        run: npx tsc ./src/**/*.ts
                     --strict
                     --outDir ./dist
                     --target es2022
                     --module node16
                     --moduleResolution node16
                     --rewriteRelativeImportExtensions

      - name: Publish to npm (next)
        if: contains(github.ref_name, '-') == true
        run: npm publish --access=public --provenance --tag=next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Publish to npm (latest)
        if: contains(github.ref_name, '-') == false
        run: npm publish --access=public --provenance --tag=latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

